### ISSUE TITLE
Swift Static Libraries

### ISSUE THREAD

**Issue by Niach** [Flash3001/Xamarin.BindingSwiftLibrarySample#1]
With Xcode 9 beta4 there was added support for creating static swift libraries.
Can this help to simplify the binding process to xamarin.ios?

**Comment by Flash3001** [comment]
Hey @Niach. 

I'm not sure it will help, because Xamarin.iOS already supports dynamic libraries. The biggest issue with the Swift bindings are the runtime libraries. 

When you work with Swift on Xcode it will automatically embed all Swift dylibs into your executable Framework folder, but when using Xamarin it doesn't happen. That is why this project exists.

Another big issue when binding Swift libraries is the difference in the naming from Swift classes and their Objective-C counterpart. If the library creator didn't explicit put a name to the Objective-C version it will receive a compiler generated name. Being so we need to explicit use this name when creating the ApiDefinition.cs class - Xamarin tool to create the initial ApiDefinition.cs won't do it.

If the library author did it, or you can do it yourself it will improve a lot the time taken to do the binding. 

On a recent binding I've worked the original library didn't inherit from NSObject (a requirement for it to work with Object-C and C#) so we had to fork it and add support. While doing it we added all the **@objc(name)** attributes to force a given Objective-C name on runtime. By doing it the binding process was almost the same as doing a normal Objective-C binding - except, of course, adding this library as a dependency on the project so it could include all the Swift runtime libraries.

You can see the @objc(name) attribute I'm talking about in here: https://github.com/FishAngler/PhoneNumberKit/blob/ac63fcd44f6b4d7796f1eeb5d1678c9afb240699/PhoneNumberKit/PhoneNumberKit.swift#L14

**Comment by Niach** [comment]
Thanks i got it all working and it works in xamarin.ios!
But when i try to include the nuget into a xamarin.ios project of an xamarin.forms app the app crashes at startup and there is no error log. i have the swift4 nugets installed.
