### ISSUE TITLE
Trouble when binding swift framework

### ISSUE THREAD

**Issue by siuhleung7** [Flash3001/Xamarin.BindingSwiftLibrarySample#2]
Hi @Flash3001 

Currently, I am doing the adyen-ios-binding which is Swift framework only and I tried to follow your tutorial from https://medium.com/@Flash3001/binding-swift-libraries-xamarin-ios-ff32adbc7c76

And based on this example
https://github.com/Adyen/adyen-ios/tree/master/Examples/Objective-C%20Example

Unfortunately, when I tried to use the binding and application will started and then quited, even I try to run this XamarinBinding also could not work (this example cannot deploy, no apps will installed)

[ApiDefinition.zip](https://github.com/Flash3001/Xamarin.BindingSwiftLibrarySample/files/2135924/ApiDefinition.zip)
[Adyen_ios_binding.framework.zip](https://github.com/Flash3001/Xamarin.BindingSwiftLibrarySample/files/2135916/Adyen_ios_binding.framework.zip)

I am finding a way to make adyen-ios works on Xamarin.iOS, could you give me a help on this??
You can feel free to contact me privatly by siuhleung7@icloud.com

Thank you very much!

**Comment by Flash3001** [comment]
Hey @siuhleung7 

Looking at the ApiDefinition.cs it seems you were trying to create the binding for the Example App itself. It won't work because you need to bind the library and recreate the example App or just use it in your own app. 

You can download their latest source code in https://github.com/Adyen/adyen-ios/releases/tag/1.18.1 

You can open the **Adyen.xcodeproj** project and rebuild the **Adyen.framework** inside the Products folder:

https://image.ibb.co/mLnvhJ/Screen_Shot_2018_07_02_at_19_18_38.png

With this code you can follow the tutorial. Step 1 to 3 will help you recompile their library code in a way that can be used on Xamarin. 

Step 6 is to include the dependencies on the App itself (not the library).

Please let me know if you need assistance =)

**Comment by siuhleung7** [comment]
Hi @Flash3001 

Thank you very much for the extremely helpful and detailed guildance!
